VIA_ENABLE = yes
LTO_ENABLE = yes

DYNAMIC_MACRO_ENABLE = yes
CONSOLE_ENABLE = no
MOUSEKEY_ENABLE = no
EXTRAKEY_ENABLE = no
COMMAND_ENABLE = no
AUDIO_ENABLE = no
NKRO_ENABLE = no
MIDI_ENABLE = no
BLUETOOTH_ENABLE = no
SPLIT_KEYBOARD = no
LEADER_ENABLE = no
